### PR TITLE
Added AddAssignment.js in components

### PR DESCRIPTION
**Pull request by chuckyim**
Hi Paola, please take a look at this PR. I added the AddAssignment.js. you can ignore the package-lock.json. Thanks.

### CODE REVIEW

**Comment by chuckyim** [comment]
@ptorre9475

**Comment by ptorre9475** [comment]
Hey Chuck, I might have missed it or possibly the files weren't tracked (this happened to me), did you add the new route to App.js and the button to the main page?

Your addAssignment component code LGTM.

**Comment by ptorre9475** [comment]
I checked the source code and the aforementioned elements are there. You can disregard my questions. It looks like it was just that those changes weren't tracked in the PR.

**Comment by chuckyim** [comment]
I believe it was because I added the button before I created the dev branch, therefore the button is already in the code. Thanks for the merge.

**Pull request merged**
